# Generated by Django 5.2.6 on 2025-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matias', models.CharField(max_length=255)),
                ('Hugo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sofia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sofia', models.CharField(max_length=255)),
                ('Poblete', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Main_app',
            new_name='Luis',
        ),
        migrations.RenameField(
            model_name='luis',
            old_name='field1',
            new_name='Luis',
        ),
        migrations.RenameField(
            model_name='luis',
            old_name='field2',
            new_name='Ochoa',
        ),
    ]
