# Generated by Django 5.2.6 on 2025-10-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_matias_sofia_rename_main_app_luis_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Luis',
            new_name='Miembro1',
        ),
        migrations.RenameModel(
            old_name='Sofia',
            new_name='Miembro2',
        ),
        migrations.RenameModel(
            old_name='Matias',
            new_name='Miembro3',
        ),
    ]
