# Generated by Django 5.2.6 on 2025-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_luis_miembro1_rename_sofia_miembro2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Miembro1',
        ),
        migrations.DeleteModel(
            name='Miembro2',
        ),
        migrations.DeleteModel(
            name='Miembro3',
        ),
    ]
