# Generated by Django 5.2.6 on 2025-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_miembros_delete_miembro1_delete_miembro2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembros',
            name='fecha_union',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='miembros',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
